name: Update GitHub Profile

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generate GitHub Streak Stats
      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true&border_radius=10
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate GitHub Contribution Snake
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile/github-contribution-grid-snake.svg
            profile/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Save generated files
      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/streak.svg
          git add profile/github-contribution-grid-snake.svg
          git add profile/github-contribution-grid-snake-dark.svg

          git commit -m "Update GitHub profile stats" || exit 0
          git push
